### ISSUE TITLE
is this port complete?

### ISSUE THREAD

**Issue by mreinstein** [darius/minilight.js#1]
according to http://www.hxa.name/minilight/#downloads  this port is still marked as "in progress". Is this still true, or has the port been completed? I'd like to help finish it if there's still work to be done.

**Comment by darius** [comment]
Harrison Ainsworth finished it, and I haven't pushed his code into this repo. I'm about to get on a plane, but I'll dig out his code this week, assuming it's not up at hxa.name already -- I'd just update the README then.

**Comment by mreinstein** [comment]
removing the burden
